# Generated by Django 3.0.4 on 2020-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200322_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flags',
            field=models.IntegerField(default=0),
        ),
    ]
